<?php
	return [
		'admin.' => ['title' => 'ダッシュボード', 'keyword' => '', 'description' => ''],

        'admin.manage.index' => ['title' => '管理者ユーザー', 'keyword' => '', 'description' => ''],
        'admin.manage.create' => ['title' => '管理者ユーザー', 'keyword' => '', 'description' => ''],
        'admin.manage.store' => ['title' => '管理者ユーザー', 'keyword' => '', 'description' => ''],
        'admin.manage.edit' => ['title' => '管理者ユーザー', 'keyword' => '', 'description' => ''],
        'admin.manage.update' => ['title' => '管理者ユーザー', 'keyword' => '', 'description' => ''],
        'admin.manage.finished' => ['title' => '管理者ユーザー', 'keyword' => '', 'description' => ''],

        'admin.user.index' => ['title' => '会員', 'keyword' => '', 'description' => ''],
        'admin.user.create' => ['title' => '会員', 'keyword' => '', 'description' => ''],
        'admin.user.store' => ['title' => '会員', 'keyword' => '', 'description' => ''],
        'admin.user.edit' => ['title' => '会員', 'keyword' => '', 'description' => ''],
        'admin.user.update' => ['title' => '会員', 'keyword' => '', 'description' => ''],
        'admin.user.finished' => ['title' => '会員', 'keyword' => '', 'description' => ''],

        'admin.post.index' => ['title' => '相談', 'keyword' => '', 'description' => ''],
        'admin.post.create' => ['title' => '相談', 'keyword' => '', 'description' => ''],
        'admin.post.store' => ['title' => '相談', 'keyword' => '', 'description' => ''],
        'admin.post.edit' => ['title' => '相談', 'keyword' => '', 'description' => ''],
        'admin.post.update' => ['title' => '相談', 'keyword' => '', 'description' => ''],
        'admin.post.end' => ['title' => '相談', 'keyword' => '', 'description' => ''],
        'admin.post.finished' => ['title' => '相談', 'keyword' => '', 'description' => ''],

        'admin.answer.index' => ['title' => '回答', 'keyword' => '', 'description' => ''],
        'admin.answer.create' => ['title' => '回答', 'keyword' => '', 'description' => ''],
        'admin.answer.store' => ['title' => '回答', 'keyword' => '', 'description' => ''],
        'admin.answer.edit' => ['title' => '回答', 'keyword' => '', 'description' => ''],
        'admin.answer.update' => ['title' => '回答', 'keyword' => '', 'description' => ''],
        'admin.answer.end' => ['title' => '回答', 'keyword' => '', 'description' => ''],
        'admin.answer.finished' => ['title' => '回答', 'keyword' => '', 'description' => ''],

        'admin.out.index' => ['title' => '出金依頼', 'keyword' => '', 'description' => ''],
        'admin.out.create' => ['title' => '出金依頼', 'keyword' => '', 'description' => ''],
        'admin.out.store' => ['title' => '出金依頼', 'keyword' => '', 'description' => ''],
        'admin.out.edit' => ['title' => '出金依頼', 'keyword' => '', 'description' => ''],
        'admin.out.update' => ['title' => '出金依頼', 'keyword' => '', 'description' => ''],
        'admin.out.end' => ['title' => '出金依頼', 'keyword' => '', 'description' => ''],
        'admin.out.finished' => ['title' => '出金依頼', 'keyword' => '', 'description' => ''],

        'admin.introduction.index' => ['title' => '紹介顧客', 'keyword' => '', 'description' => ''],
        'admin.introduction.create' => ['title' => '紹介顧客', 'keyword' => '', 'description' => ''],
        'admin.introduction.store' => ['title' => '紹介顧客', 'keyword' => '', 'description' => ''],
        'admin.introduction.edit' => ['title' => '紹介顧客', 'keyword' => '', 'description' => ''],
        'admin.introduction.update' => ['title' => '紹介顧客', 'keyword' => '', 'description' => ''],
        'admin.introduction.end' => ['title' => '紹介顧客', 'keyword' => '', 'description' => ''],
        'admin.introduction.finished' => ['title' => '紹介顧客', 'keyword' => '', 'description' => ''],
    ];
