version: '3'

services:
  php:
    image: ${DOCKER_NAME}_php
    container_name: ${DOCKER_NAME}_php
    build: ./php
    volumes:
        - ../:/var/www/html
    working_dir: /var/www/html
  cron:
    image: ${DOCKER_NAME}_cron
    container_name: ${DOCKER_NAME}_cron
    build: ./cron
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    build:
      context: ./../
      dockerfile: ./docker/web/Dockerfile
    image: ${DOCKER_NAME}_web
    container_name: ${DOCKER_NAME}_web
    volumes:
      - ../:/var/www/html
    restart: always
    environment:
        VIRTUAL_HOST: ${DOMAIN}
        LETSENCRYPT_HOST: ${DOMAIN}
        LETSENCRYPT_EMAIL: ${DOMAIN}
        PHP_HOST: ${PHP_HOST}
        PHP_PORT: ${PHP_PORT}
    depends_on:
      - php
    command: /bin/sh -c "envsubst '$$PHP_HOST$$PHP_PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
networks:
  default:
    external:
      name: shared
